print("\n Monday Red")
print("1. Dialogue II")
print("2. Specials")
print("3. Research Principles B")
print("4. Lunch & Office Hours")
print("5. Chemistry B")

print("\n Monday Black")
print("1. English B")
print("2. Latin III")
print("3. History")
print("4. Lunch & Office Hours")
print("5. Algebra II")

print("\n Tuesday")
print("1. Music 10")
print("2. Chemistry B")
print("3. Intro To Computer Science B")
print("4. Lunch")
print("5. Algebra II")
print("6. Latin III")
print("7. English 10")

print("\n Wednesday")
print("1. History")
print("2. Dialogue II")
print("3. Latin III")
print("4. Lunch")
print("5. Chemistry B")
print("6. Music 10")

print("\n Thursday")
print("1. Chemistry B")
print("2. English 10")
print("3. Algebra II")
print("4. Lunch")
print("5. Research Principles")
print("6. Community Time")
print("7. History 10")

print("\n Friday")
print("1. Latin III")
print("2. Algebra II")
print("3. English 10")
print("4. Lunch")
print("5. History 10")
print("6. Intro To Computer Science B")
